name: Render Video

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: "项目名称"
        required: true
        type: string

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies & Configure system
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev ffmpeg locales language-pack-zh-hans

          sudo locale-gen zh_CN.UTF-8
          echo "LANG=zh_CN.UTF-8" | sudo tee /etc/default/locale
          export LANG=zh_CN.UTF-8

          sudo mkdir -p /usr/share/fonts/custom-fonts
          sudo cp -R $GITHUB_WORKSPACE/assets/fonts/ /usr/share/fonts/custom-fonts/
          sudo find /usr/share/fonts/custom-fonts -type d -exec chmod 755 {} \;
          sudo find /usr/share/fonts/custom-fonts -type f -exec chmod 644 {} \;
          sudo fc-cache -fv
          fc-list | grep "/custom-fonts/"

          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore media cache
        uses: actions/cache/restore@v4
        with:
          path: |
            media/texts
            media/videos/main/2160p60/partial_movie_files
          key: media

      - name: Render video
        run: python main.py prod ${{ inputs.project_name }}

      - name: Save media cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            media/texts
            media/videos/main/2160p60/partial_movie_files
          key: media

      - name: Copy video
        run: |
          mkdir -p video_artifacts
          find media/videos/main/2160p60 -maxdepth 1 -type f -exec cp -v {} video_artifacts/ \;
          ls -lh video_artifacts

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.project_name }}
          path: video_artifacts/*
